project_id = "yhyveqffsitdgwyflvgp"

[functions.start-response]
verify_jwt = false

[functions.submit-answer]
verify_jwt = false

[functions.navigate-back]
verify_jwt = false

[functions.resume-response]
verify_jwt = false

[functions.process-integrations]
verify_jwt = false

[functions.save-integration-secret]
verify_jwt = true

[functions.preview-template]
verify_jwt = true

[functions.run-integration-test]
verify_jwt = true
